"""create all tables

Revision ID: 22ab938d03a5
Revises: 
Create Date: 2026-06-06 17:57:07.195346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ab938d03a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutoff_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_code', sa.String(), nullable=True),
    sa.Column('branch_code', sa.String(), nullable=True),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('predicted_cutoff_rank', sa.Integer(), nullable=True),
    sa.Column('last_year_cutoff', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cutoff_cache_id'), 'cutoff_cache', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('maths', sa.Float(), nullable=True),
    sa.Column('physics', sa.Float(), nullable=True),
    sa.Column('chemistry', sa.Float(), nullable=True),
    sa.Column('aggregate', sa.Float(), nullable=True),
    sa.Column('marks_locked', sa.Boolean(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rank_phase', sa.String(), nullable=True),
    sa.Column('has_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('maths', sa.Float(), nullable=True),
    sa.Column('physics', sa.Float(), nullable=True),
    sa.Column('chemistry', sa.Float(), nullable=True),
    sa.Column('aggregate', sa.Float(), nullable=True),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('predicted_rank_low', sa.Integer(), nullable=True),
    sa.Column('predicted_rank_high', sa.Integer(), nullable=True),
    sa.Column('college_code', sa.String(), nullable=True),
    sa.Column('branch_code', sa.String(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_table('rank_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actual_rank', sa.Integer(), nullable=True),
    sa.Column('aggregate', sa.Float(), nullable=True),
    sa.Column('community', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_inputs_id'), 'rank_inputs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rank_inputs_id'), table_name='rank_inputs')
    op.drop_table('rank_inputs')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cutoff_cache_id'), table_name='cutoff_cache')
    op.drop_table('cutoff_cache')
    # ### end Alembic commands ###
