"""add application_id to users

Revision ID: 8788ce6dd9a2
Revises: fc467bc796ab
Create Date: 2026-06-09 23:00:14.989132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8788ce6dd9a2'
down_revision: Union[str, Sequence[str], None] = 'fc467bc796ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('application_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'application_id')
    # ### end Alembic commands ###
