"""add preferred colleges and courses to users

Revision ID: fc467bc796ab
Revises: 22ab938d03a5
Create Date: 2026-06-09 18:32:06.456109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc467bc796ab'
down_revision: Union[str, Sequence[str], None] = '22ab938d03a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_colleges', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferred_courses', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_courses')
    op.drop_column('users', 'preferred_colleges')
    # ### end Alembic commands ###
